repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace