# Образы для контейнера
FROM ghcr.io/vlmhyperbenchteam/qwen2.5-vl:ubuntu22.04-cu124-torch2.4.0_v0.1.0

# Отключаем интерактивные вопросы при установке пакетов
ARG DEBIAN_FRONTEND=noninteractive

# Установка китайского mirror (например, Alibaba mirror)
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple

# Установка библиотек
RUN pip install --no-cache-dir peft==0.14.0 bitsandbytes==0.46.0 datasets==3.2.0 gdown==5.2.0
RUN pip install --no-cache-dir git+https://github.com/VLMHyperBenchTeam/model_qwen2.5-vl.git@0.1.0
RUN pip install --no-cache-dir scikit-learn==1.6.1

# Создаем рабочую директорию
WORKDIR /workspace

# Запускаем терминал
CMD ["/bin/bash"]